### ISSUE TITLE
Error while search for emoji

### ISSUE THREAD

**Issue by 0wx** [jarun/googler#375] opened 2020-10-03 22:16 UTC
```Bash
$ googler lion emoji
No results.
If you believe this is a bug, please review https://git.io/googler-no-results before submitting a bug report.
```

I used your tools to find emoji without opening browser or any app. Its still working yesterday, now it cannot show any of emoji in the terminal after I update things.

**Comment by jarun** [comment] 2020-10-03 23:54
This is probably a duplicate of #372. Please test with master (which has the fix) and confirm.

**Closed** 2020-10-05 01:58 UTC
