### ISSUE TITLE
Using googler in Windows

### ISSUE THREAD

**Issue by lhaisrs** [jarun/googler#169] opened 2017-03-01 19:00 UTC
I started using googler in Windows and i did what is the #70 but still not working. I'm using the Python 3.5.1 version. The bug is: **UnicodeEncodeError: 'charmap' codec can't encode character '\u2022' in position 0: character maps to <undefined>**

How can i fix it?

**Comment by zmwangx** [comment] 2017-03-01 19:03
Please follow the issue template and provide additional information, which is vital for troubleshooting:

---

Before opening an issue, please try to reproduce on [the latest development version](https://github.com/jarun/googler#installing-from-this-repository) first. The bug you noticed might have already been fixed.

If the issue can be reproduced on master, then please make sure you provide the following:
- Output of `googler -d`;
- Link to the response body (you should see a line like `[DEBUG] Response body written to '/Volumes/ramdisk/googler-response-xxxxxxxx'` in the output of `googler -d`; please upload the file to a [gist](https://gist.github.com/) and include the gist's URL in the issue);
- Details of operating system, Python version used, terminal emulator and shell;
- `locale` output, if relevant. It's a good idea to set your locale to UFT-8. Please refer to [Buku #30](https://github.com/jarun/Buku/issues/30).

**Comment by lhaisrs** [comment] 2017-03-01 19:13
This is my output: 

 1  Google
https://www.google.com.br/
Versão brasileira do popular buscador e diretório. Utiliza também os dados do ODP.

 2  Google
https://www.google.com/?hl=pt_br
Português. Pesquisa avançadaFerramentas de idioma · Soluções de publicidadeSobre o GoogleGoogle.com in English. © 20
- Privacidade - Termos.

 3  Google | Facebook
https://www.facebook.com/Google/
Google, Mountain View, CA. 21883539 likes · 66399 talking about this. Organizing the world's information and making
universally accessible and useful.

 4  Google - YouTube
https://www.youtube.com/user/Google
Experience the world of Google on our official YouTube channel. Watch videos about our products, technology, company
happenings and more. Subscribe to ...

 5  Google - TecMundo
https://www.tecmundo.com.br/google
Google Spaces será desligado e apagado da web no dia 17 de abril. Imagem de Conheça três sites brasileiros para vend
compra de celulares usados no ...

 6  Google (@Google) | Twitter
https://twitter.com/google
66.9K tweets Traceback (most recent call last):
  File "googler.py", line 757, in <module>
    results = fetch_results()
  File "googler.py", line 741, in fetch_results
    r.print_entry()
  File "googler.py", line 341, in print_entry
    print(w, end=' ')
  File "C:\Users\lhais\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2022' in position 0: character maps to <undefined>

When I set python googler.py G

**Comment by zmwangx** [comment] 2017-03-01 19:21
Not sure why you deleted your comment and closed the issue, but since you got

```python-traceback
File "googler.py", line 757, in 
results = fetch_results()
File "googler.py", line 741, in fetch_results
r.print_entry()
File "googler.py", line 341, in print_entry
print(w, end=' ')
File "C:\Users\lhais\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp850.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2022' in position 0: character maps to
```

apparently your output encoding is `cp850` Western Europe. Setting `PYTHONIOENCODING` to `utf-8` should probably fix it. I'm already checking this in #152, but I excluded Windows in that PR because I simply don't know enough about Windows to make sure I don't screw up and totally bust it for Windows users.

**Comment by zmwangx** [comment] 2017-03-01 19:27
By the way, your case is strange because according to [docs](https://docs.python.org/3/library/sys.html#sys.stdout)

> The character encoding is platform-dependent. Under Windows, if the stream is interactive (that is, if its isatty() method returns True), the console codepage is used, otherwise the ANSI code page. Under other platforms, the locale encoding is used (see locale.getpreferredencoding()).

If you followed my advice of `chcp 65001` then your output encoding should be `cp65001` (that is, Windows UTF-8, or `CP_UTF8`). So either

- You didn't `chcp 65001` (but you said you did...) or somehow it didn't take effect; IIRC you can check the code page in PowerShell's preference pane. Or
- The docs are inaccurate. In that case... Well, I'm not interested enough to read the Windows branches of CPython source code.

**Comment by lhaisrs** [comment] 2017-03-01 19:28
Sorry, I'm not good english writter and I'm noob using Github. I closed unintentionally.

I'll try it, thanks for your help.

**Comment by zmwangx** [comment] 2017-03-01 19:28
No problem.

**Comment by jarun** [comment] 2017-03-12 14:56
I am closing this defect as the reporter didn't get back. Please feel free to reopen, if you have some data to share.

**Closed by jarun** 2017-03-12 14:56 UTC
