### ISSUE TITLE
googler -N throws error

### ISSUE THREAD

**Issue by LaChirla** [jarun/googler#398] opened 2021-04-17 09:58 UTC
lately the call:
googler -N 'Biden'  
results in:
[ERROR] DOM builder aborted at 1069:345: expecting end tag 'div', got 'body'

thank you.,

**Comment by jarun** [comment] 2021-04-17 11:02
I don't see this:

```
$ googler -N 'Biden'                                        

 1.  4 Sikhs among 8 killed in US FedEx shooting; India, President Biden express shock [indianexpress.com]
     The Indian Express, 1 hour ago
     Following the incident, US President Joe Biden ordered the national flag to be flown half-staff at
     the White House and all federal buildings.

 2.  10 Democrats Ask Biden To Back India's Waiver Bid At WTO [www.ndtv.com]
     NDTV.com, 11 hours ago
     Ten Democratic Senators led by influential Bernie Sanders have urged US President Joe Biden to
     support India and South Africa's proposal to...

 3.  President Biden`s new policy is an act of vaccine mafia! USA halts import of crucial raw material [zeenews.india.com]
     Zee News, 19 hours ago
     Serum Institute of India (SII) Chief Executive Adar Poonawalla has urged US President Joe Biden to
     lift the export ban on critical raw materials...

 4.  Sanders, Warren, 8 others tell Joe Biden to go for vaccine IPR waiver [timesofindia.indiatimes.com]
     Times of India, 8 hours ago
     NEW DELHI: Ten prominent American senators, including Bernie Sanders and Elizabeth Warren, have
     asked US President Joe Biden to...

 5.  Serum's Adar Poonawalla urges Joe Biden: Lift embargo on Covid vaccine raw material exports [www.livemint.com]
     Mint, 1 day ago
     Serum Institute of India (SII) Chief Executive Adar Poonawalla on Friday appealed to US President
     Joe Biden to lift the US embargo on...

 6.  10 Democratic Senators asks Joe Biden to back India's move to get TRIPS waiver to COVID vaccines at WTO [www.cnbctv18.com]
     CNBCTV18, 17 hours ago
     Ten Democratic Senators led by influential Bernie Sanders have urged US President Joe Biden to
     support India and South Africa's proposal to...

 7.  Shortage of vaccine raw materials, SII CEO to Biden: End export embargo [indianexpress.com]
     The Indian Express, 11 hours ago
     Serum Institute of India CEO Adar Poonawalla Friday urged US President Joe Biden to lift the embargo
     on export of raw materials needed to...

 8.  President Biden, suspend intellectual property rights on Covid vaccines [timesofindia.indiatimes.com]
     Times of India, 1 day ago
     A mixed group of more than a 100 prominent people, including former UK Prime Minister Gordon Brown,
     have reportedly written to the US...

 9.  Over 60 former leaders, 100 Nobel Prize winners urge Biden to back India's COVID-19 vaccine waiver plea [www.businesstoday.in]
     Business Today, 2 days ago
     A waiver would boost vaccine manufacturing and speed up the response to the pandemic in poorer
     countries which otherwise might have to...

googler (? for help)
```

**Comment by patri9ck** [comment] 2021-04-18 16:26
I have the same issue.

```
googler -C --np -N gadgets
[ERROR] DOM builder aborted at 1067:345: expecting end tag 'div', got 'body'
```

**Comment by jarun** [comment] 2021-04-18 22:21
What is your googler version?

**Comment by patri9ck** [comment] 2021-04-18 22:37
```
$ googler --version
4.3.2
```
I am on Arch Linux using the package from the AUR.

**Comment by jamulix** [comment] 2021-04-21 16:03
$ googler -C --np -N 'Bitcoin'
[ERROR] DOM builder aborted at 1069:345: expecting end tag 'div', got 'body'

detected on 20121 April 1
$ googler --version
4.3.2

**Comment by jarun** [comment] 2021-04-21 16:10
We need to wait for @zmwangx or someone else to take a look at result html and the parser.

**Comment by zmwangx** [comment] 2021-04-25 04:25
Since the issue doesn’t follow the very clear instructions in the issue template in providing debug output and attaching HTML, and I can’t reproduce this myself, it’s simply not actionable. Please don’t ignore instructions, it wastes the time of everyone involved. Closing. If anyone provides actionable info in accordance with the issue template, the issue can be reopened.

**Closed by zmwangx** 2021-04-25 04:25 UTC

**Comment by jarun** [comment] 2021-04-25 10:06
@zmwangx if time permits, please check the daily CI failure: https://github.com/jarun/googler/actions
