### ISSUE TITLE
Country-specific search does not work

### ISSUE THREAD

**Issue by 465788227** [jarun/googler#347] opened 2020-06-05 04:58 UTC
-c tag doesn't have any effect at all
> OS: NetBSD 9
> `$ googler -d -c us 'news'`
> [DEBUG] googler version 4.1
> [DEBUG] Python version 3.7.7 (also tested 3.8.3)
> [DEBUG] Connecting to new host www.google.com
> [DEBUG] Fetching URL /search?hl=en&ie=UTF-8&oe=UTF-8&q=news&sei=YXW89Kc5Eeqb9hwbDREuTA
> [DEBUG] Cookie: 1P_JAR=2020-06-05-14
> [DEBUG] Response body written to '/tmp/googler-response-jpavozvu.html'.

**Comment by zmwangx** [comment] 2020-06-05 05:53
Need way more details than "does not work". We provide an issue template for a reason. Please go to https://github.com/jarun/googler/issues/new, copy the template, fill it out and edit it into the issue. Let us know when you've done that. Otherwise we'll close the issue in a day.

**Comment by 465788227** [comment] 2020-06-05 14:36
There's a similar topic but you didn't solved that.
https://github.com/jarun/googler/issues/265

**Comment by zmwangx** [comment] 2020-06-05 15:50
The “US-specific” version of Google is just www.google.com, so working as intended. Closing, but let me know if there are follow up questions.

**Closed by zmwangx** 2020-06-05 15:50 UTC

**Comment by 465788227** [comment] 2020-06-05 15:54
I'm not in the U.S., change -c with 'in', 'fr'... all give the only same results that in my local country.

**Comment by zmwangx** [comment] 2020-06-05 16:01
If you look at debug output you’ll notice that you’re being connected to google.co.in with -c in, and google.fr with -c fr (if that’s not the case, then you actually hit a bug and we’d like to know that). But other versions of Google returning the same results for most queries is both expected and beyond our control. I think you’re misinterpreting what country-specific search actually does which led to misaligned expectations.

**Comment by zmwangx** [comment] 2020-06-05 16:03
Btw, instead of looking at debug output, you can also use the ‘o’ command in the prompt to open the search results page and confirm you’re on a different version of Google.

**Comment by 465788227** [comment] 2020-06-05 16:08
Yes, it changes the domain. I'm quite surprised that you want to know the problem, but don't even care that the result doesn't change at all. It's about cookies!

**Comment by zmwangx** [comment] 2020-06-05 16:19
I “don’t even care that results doesn’t change at all” because we’re not in the business of curating results, if different Google domains show you the same results in the browser, googler should show you the same results. We fetch the results and display them, that’s all. And I can tell you the results aren’t always the same, for instance certain things are blocked in certain Google domains on legal grounds but not in others, or at least it used to be the case. So it’s certainly not useless.

But if you have actionable info about why you think it’s about cookies, we’re open to change.

**Comment by jarun** [comment] 2020-06-05 16:38
> I'm surprised that you want to know the problem, but don't even care that the result doesn't change at all. Changing domain is useless. It's about cookies. Hope you can fix that!

Excuse me! It's possible we misunderstand the problem but we are in no way under any commitment that we will fix every issue or feature we don't even use.

If it's so important to you feel free to fix it yourself.

**Comment by 465788227** [comment] 2020-06-05 16:40
Query string can change language, but domain does nothing.
I think you're in the U.S. and don't even care about changing regions in Google settings will show totally different results. If you want to fix that. You should remove -c tag feature to not waste people's time.

**Comment by zmwangx** [comment] 2020-06-05 16:51
Sure, with actionable information I can look into it. Kudos to removing the confrontational bit.

**Comment by zmwangx** [comment] 2020-06-05 17:10
Okay, looked into it. Region settings is persisted through the `NID` cookie. The `NID` cookie comes from a `Set-Cookie` header within the response of a request to https://www.google.com/setprefs with the following query params:

```py
{'sig': ['...'],
 'submit2': ['Save Preferences'],
 'hl': ['en'],
 'lang': ['en'],
 'lr': ['lang_en'],
 'safeui': ['images'],
 'num': ['0'],
 'tts': ['1'],
 'newwindow': ['0'],
 'gl': ['AL'],
 'region': ['AL'],
 'prev': ['https://www.google.com/search?...']}
```

I didn't bother to trace how `sig`'s generated.

So, my assessment: this is possible, but requires a preflight (and a bit of reverse engineering). The result should be cacheable, but googler explicitly promised not to touch the disk, which makes it a much harder decision to make. I'm neutral on whether this should be implemented, but it won't come from me. If you'd like to contribute a patch I'm open to reviewing and polishing it; and @jarun please weigh in on architectural decisions here if possible (no rush).

As for removing this option, I know @jarun uses `-c in` himself to avoid a redirect, so we won't remove it.

**Comment by zmwangx** [comment] 2020-06-05 17:15
Of course there's another possibility: someone could reverse engineer the `NID` cookie to see if we can generate it without preflight. That someone won't be me though.
