### ISSUE TITLE
"No results" for every search

### ISSUE THREAD

**Issue by webctrl** [jarun/googler#298] opened 2019-11-09 13:07 UTC
Hello,

I'm new to GitHub, so I hope I'm doing this right. I woke up today to find that googler now returns no results for whatever I search. I was using version 3.9, and have also tried the master (which I think is also 3.9).

My main PC is Arch Linux, Python version 3.7.4, xfce4-terminal, BASH. I also tried it on a Raspberry Pi running Raspbian and had the same result.

**Debug info:**

```
[DEBUG] googler version 3.9
[DEBUG] Python version 3.7.4
[DEBUG] Connecting to new host www.google.com
Please initiate a query.
googler (? for help) test
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=test&sei=XcgUTALvEeqX4shgAHXQAQ
[DEBUG] Got exception: Remote end closed connection without response.
[DEBUG] Attempting to reconnect...
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=test&sei=XcgUTALvEeqX4shgAHXQAQ
[DEBUG] Cookie: 1P_JAR=2019-11-09-12
[DEBUG] Response body written to '/tmp/googler-response-1p0lslp8.html'.
No results.
```

**Response body:**

I tried to add the response body to a gist, but GitHub wouldn't let me make the gist public. I've contacted them to find out what I'm doing wrong. For now I've put the response body in a pastebin:

https://pastebin.com/raw/zMKnRvQt

**Comment by zmwangx** [comment] 2019-11-13 03:55
Dupe of #299. Problem should be gone by now. Please reopen if the problem persists for you (but we probably won't do anything unless the problem is clearly persistent widespread).

**Closed by zmwangx** 2019-11-13 03:55 UTC
