### ISSUE TITLE
incorrect encoding of prompt

### ISSUE THREAD

**Issue by urielz** [jarun/googler#203] opened 2017-09-22 17:42 UTC
Googler 3.3 is working for me on OS X Capitan except that the prompt is a bit messed up (see screenshot) Any tips on how to fix this? Thanks!

![image](https://user-images.githubusercontent.com/11670888/30757201-c9a80dde-9f9b-11e7-85db-75597c481d64.png)

**Comment by zmwangx** [comment] 2017-09-22 17:44
Your terminal emulator doesn't support reverse video (`\e[7m`). What terminal emulator is this?

**Comment by urielz** [comment] 2017-09-22 17:59
I use iterm2 (https://www.iterm2.com/) but the OS X default terminal has the same issue..

**Comment by zmwangx** [comment] 2017-09-22 18:04
That doesn't sound right at all. I'm an iTerm2 user on macOS. Please run

```
yes q | \googler hello >/tmp/googler.output
```

and upload `/tmp/googler.output` to gist.github.com. Make sure you don't lose any characters in the process (you can download the file yourself and compare the checksum to the original). I'll have a look.

**Comment by zmwangx** [comment] 2017-09-22 18:05
Actually,

```
yes q | \googler hello | pbcopy
```

would be easier.

**Comment by urielz** [comment] 2017-09-22 18:12
here's the output:
https://gist.github.com/urielz/566fd84ccdb105aa98639f4b82108b98

**Comment by urielz** [comment] 2017-09-22 18:16
something that might help - If I pbpaste the output of yes q | \googler hello | pbcopy then the characters are encoded correctly...

**Comment by zmwangx** [comment] 2017-09-22 18:16
Prints just fine here. iTerm2 3.1.20170919-nightly, macOS 10.12.6. `TERM` is `xterm-256color`. See screenshot below for Preferences->Profiles->Terminal->Terminal Emulation setting. I don't think you would be any different on El Cap; reverse video is extremely basic stuff.

<img width="951" alt="screen shot 2017-09-22 at 2 13 01 pm" src="https://user-images.githubusercontent.com/4149852/30758386-31101d50-9fa0-11e7-9ab7-3f359e32dbc2.png">

<img width="489" alt="screen shot 2017-09-22 at 2 15 43 pm" src="https://user-images.githubusercontent.com/4149852/30758479-9d459a36-9fa0-11e7-875c-766caee6f101.png">

You might want to check this on a clean VM if you can.

**Comment by zmwangx** [comment] 2017-09-22 18:17
> something that might help - If I pbpaste the output of yes q | \googler hello | pbcopy then the characters are encoded correctly...

Okay that's something. But this is not an "encoding" issue; it's not like `\x1b` is somehow wrongly "encoded", you're getting colors just fine.

**Comment by urielz** [comment] 2017-09-22 18:18
UTF-8 xterm256 is my setup as well. I'll report back if I manage to fix it just in case someone else runs into this. Thanks for the help!

**Comment by zmwangx** [comment] 2017-09-22 18:21
Another way to debug that I can think of is to use iTerm2's session logging. It logs every character printed to the terminal verbatim, so that's something to check. To enable, go to Profiles->Session->Miscellaneous->Automatically log session input to files in:.

**Comment by urielz** [comment] 2017-09-22 18:36
Thanks. I will take a proper look when I find the time. For now I modified the line of code so it won't do reverse video. Feel free to close this, looks like it's an issue with my system anyway.

**Comment by zmwangx** [comment] 2017-09-22 18:38
You don't need to modify the code. You can set the prompt to a host of color/styles other than reverse video. Read https://github.com/jarun/googler#colors.

**Comment by zmwangx** [comment] 2017-09-22 18:40
Closing for now. Let us know if there's anything wrong with our code.

**Comment by urielz** [comment] 2017-09-22 19:01
ok so this issue seems to be beyond reverse color. Using the --colors I can change all colors except for the prompt colors.

For example: googler --colors GKlgxa will give a prompt like this:
[30mgoogler (? for help)[0m

or googler t --colors GKlgxj 
[91mgoogler (? for help)[0m

**Comment by jarun** [comment] 2017-09-23 00:58
What happens if you set the prompt to normal?

    googler t --colors GKlgxx?

**Comment by jarun** [comment] 2017-09-23 01:00
And please try the `-C` option as well.

**Comment by jarun** [comment] 2017-09-23 01:01
@zmwangx pinging you on Gitter for something else.

**Comment by zmwangx** [comment] 2017-09-23 02:28
The only thing different about this prompt (from other colored stuff) is it's wrapped in an `input` call. So I would run the following simply script and see what happens

```py
#!/usr/bin/env python3
input('\x1b[31mThis is a red prompt: \x1b[0m')
```

**Comment by urielz** [comment] 2017-09-25 13:24
@jarun:  the output of googler t --colors GKlgxx is:
[0mgoogler (? for help)[0m

and -C seems to work fine:
googler (? for help):

@zmwangx: I can see the red prompt with the script.

**Comment by jarun** [comment] 2017-09-25 13:52
OK. In order to narrow it down, what happens if you just run `googler`? Without any options. Same issue?

**Comment by jarun** [comment] 2017-09-25 14:40
In addition to my comment above, can you check if the following patch makes any difference?

```
diff --git a/googler b/googler
index a170c30..e6132d1 100755
--- a/googler
+++ b/googler
@@ -1620,11 +1620,13 @@ class Result(object):
             fillwidth = columns - indent - 1
             for line in textwrap.wrap(abstract.replace('\n', ''), width=fillwidth):
                 print('%s%s' % (' ' * indent, line))
-            print('')
         else:
-            print('%s\n' % abstract.replace('\n', ' '))
+            print('%s' % abstract.replace('\n', ' '))
+
         if colors:
-            print(colors.reset, end='')
+            print(colors.reset, end='\n')
+        else:
+            print('')
 
     def print(self):
         """Print the result entry."""
```

I can't think of any reason why it should yet, still...

**Comment by urielz** [comment] 2017-09-25 16:12
yes I'm using an alias (alias news='googler -n 5 -N --url-handler reader').

But executing /usr/local/bin/googler gives the prompt:
7mgoogler (? for help)[0m

I tried the patch but still same result. Googler is working great for me except for this issue- which I can work around it by changing that line of code (to have no colors at all in the prompt). But I'm happy to keep on helping debug this is you think there's a problem with the code and you would like to pursue it...

**Comment by jarun** [comment] 2017-09-25 16:16
What happens if you add the color codes manually to the message (instead of using the colors subsystem)? Does it show correctly?

**Comment by urielz** [comment] 2017-09-25 16:32
I think the problem is input(). check this: https://bugs.python.org/issue17337

**Comment by jarun** [comment] 2017-09-25 16:47
Unfortunately, I can't reproduce this myself to test anything. I'll have to bank of you and @zmwangx to figure out something.

In any case, this isn't _critical_ so I'm fine even if we don't have a patch.

**Closed** 2017-09-26 08:01 UTC

**Comment by jarun** [comment] 2017-12-11 20:36
@urielz I hope the latest commit provides you a better experience.

**Comment by urielz** [comment] 2018-02-08 15:02
> export DISABLE_PROMPT_COLOR=1

@jarun thank you! yes this works.

**Comment by jarun** [comment] 2018-02-08 17:02
My pleasure!
