### ISSUE TITLE
Connection blocked due to unusual activity

### ISSUE THREAD

**Issue by suuuehgi** [jarun/googler#323] opened 2020-03-03 17:33 UTC
#### Bug reports

Same as in the already closed issues (e.g. #244).

```
> googler -d test
[DEBUG] googler version 4.0
[DEBUG] Python version 3.8.1
[DEBUG] Connecting to new host www.google.com
[DEBUG] Fetching URL /search?ie=UTF-8&oe=UTF-8&q=test&sei=kLbGTF1rEeqmZDzhoVDDxA
[DEBUG] Cookie: 1P_JAR=2020-03-03-16
Traceback (most recent call last):
  File "/usr/bin/googler", line 3428, in <module>
    main()
  File "/usr/bin/googler", line 3417, in main
    repl.cmdloop()
  File "/usr/bin/googler", line 2861, in cmdloop
    self.fetch_and_display()
  File "/usr/bin/googler", line 2469, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/bin/googler", line 2669, in fetch_and_display
    self.fetch()
  File "/usr/bin/googler", line 2469, in enforced_method
    method(self, *args, **kwargs)
  File "/usr/bin/googler", line 2569, in fetch
    page = self._conn.fetch_page(self._google_url.relative())
  File "/usr/bin/googler", line 2085, in fetch_page
    raise GoogleConnectionError(msg)
__main__.GoogleConnectionError: Connection blocked due to unusual activity.
```

I'm thinking about whether its the HTTP protocol being used.

`curl` uses HTTP/2, the used python package `http.client.HTTPSConnection` afaik only supports v1.1.

**Gets the blocked page**
```python
import requests
headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0',
}

params = (
    ('ie', 'UTF-8'),
    ('oe', 'UTF-8'),
    ('q', 'test'),
    ('sei', 'uldT8F1lEeqqbjzhoVDDxA'),
)

html = requests.get('https://www.google.com/search', headers=headers, params=params).text
```

**Gets the real page**
```python
import subprocess
html = subprocess.check_output(['curl', 'https://www.google.com/search?ie=UTF-8&oe=UTF-8&q=test&sei=uldT8F1lEeqqbjzhoVDDxA', '-H', 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0']).decode('utf-8')
```

Maybe googler could just use another request method.

**Comment by jarun** [comment] 2020-03-04 01:02
We can check this out. However, it happens in the standard browser too when you abuse the search by sending repeated requests in succession.

Can you check if curl works when googler is blocked for you?

**Comment by suuuehgi** [comment] 2020-03-04 15:28
> Can you check if curl works when googler is blocked for you?

Sorry for the brevity. Googler hasn't worked a single time so far. Standard `curl` neither.

The aforementioned user-agent makes the difference for me:

```bash
# Doesn't work
curl $URL

# Works
curl $URL -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0'
```

But just setting the user-agent in Googler is not doing it. I already tried this and other things. :)

**Comment by jarun** [comment] 2020-03-04 15:36
The default agent works for me. This probably has something to do with geoilocation than with the agent.

**Comment by jarun** [comment] 2020-03-04 15:37
If you want to explore, try using the [requests](https://requests.readthedocs.io/en/master/) library in `googler` and see if that works.

**Comment by suuuehgi** [comment] 2020-03-04 15:57
> If you want to explore, try using the [requests](https://requests.readthedocs.io/en/master/) library in `googler` and see if that works.

Thanks for your reply! I already tried the [curl to requests](https://curl.trillworks.com/) converter without success.

**Comment by jarun** [comment] 2020-03-04 16:20
In that case, try a proxy with `googler`.

**Comment by zmwangx** [comment] 2020-03-04 17:18
It highly depends on IP reputation. Some IPs (e.g. my Newark, NJ Linode IPs) get blocked every single time. Some other non-residential IPs I've used won't. Commercial VPN services are pretty much guaranteed to be blocked both from my personal experience and what I heard.

I doubt this has anything to do with HTTP/2, but in any case we can't really any HTTP/2 unless PSL adds support for it. It's a complicated protocol btw, even urllib3 and by extension requests don't support it. There's been talk for more than half a decade too. bpo-23794: https://bugs.python.org/issue23794

**Comment by suuuehgi** [comment] 2020-03-05 14:27
@zmwangx Thank you -- that sounds reasonable. So, it seems apart from really digging into this, there is currently nothing I can do about it.

@jarun I'm not that familiar with the code base -- could you tell me whether there is a simple way to replace the `HTTPSConnection` with a plain simple `curl` via `subprocess` e.g. as described above?

**Comment by jarun** [comment] 2020-03-05 14:32
> could you tell me whether there is a simple way to replace the current fetching with a plain simple curl via subprocess e.g. as described above?

I am afraid there isn't without messing around with the decoding logic. The simplest solution would be to use a proxy.

**Comment by zmwangx** [comment] 2020-03-05 16:36
> could you tell me whether there is a simple way to replace the current fetching with a plain simple curl via subprocess e.g. as described above?

Here's a quick and dirty patch to do what you want.

```diff
diff --git a/googler b/googler
index e8246e1..b06fef4 100755
--- a/googler
+++ b/googler
@@ -2070,6 +2070,12 @@ class GoogleConnection(object):
             Response payload, gunzipped (if applicable) and decoded (in UTF-8).
 
         """
+        import subprocess
+        # Add or modify curl options as you need.
+        return subprocess.check_output([
+            'curl', '-sS', '-A', USER_AGENT, urllib.parse.urljoin('https://' + self._host, url)
+        ]).decode('utf-8')
+
         try:
             self._raw_get(url)
         except (http.client.HTTPException, OSError) as e:
```

Confirmed to work, btw.

**Comment by jarun** [comment] 2020-03-05 16:50
Yes, that works. I thought it would need more than `decode('utf-8')` to fit into `googler`! :+1:

**Comment by jarun** [comment] 2020-03-05 16:50
Closing this defect with the above solution shared by @zmwangx.

**Closed by jarun** 2020-03-05 16:50 UTC
