### ISSUE TITLE
Recent error message

### ISSUE THREAD

**Issue by 621625** [jarun/googler#431] opened 2021-11-26 12:23 UTC
Hello,

I'm MB. A very nice and polite guy.

This package is very useful.

Recently it gives the following error message though:

DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
Please initiate a query.

Any ideas on how to fix it?

**Comment by jarun** [comment] 2021-11-26 12:51
Duplicate of #425. Fixed on master.

**Closed as completed by jarun** 2021-11-26 12:51 UTC
