### ISSUE TITLE
Doesn't check for the proxy

### ISSUE THREAD

**Issue by luviiit** [jarun/googler#35] opened 2016-02-25 18:19 UTC
Can you please change the code to detect the proxy settings

**Comment by jarun** [comment] 2016-02-25 18:22
Duplicate of issue #20. Please consider sparing some time to implement the feature if the solution offered doesn't suit you.

**Closed by jarun** 2016-02-25 18:22 UTC

**Comment by zmwangx** [comment] 2016-02-25 23:17
Experimental HTTP proxy support has been added https://github.com/jarun/googler/blob/master/googler#L393. Please help by testing it or contributing insight/code if you want to see it merged.

**Comment by luviiit** [comment] 2016-02-26 06:46
I ran 
`$ ./googler -y proxy.iiit.ac.in:8080 hello`
and following error occured
`[DEBUG] Exception: [Errno 101] Network is unreachable`

**Comment by zmwangx** [comment] 2016-02-26 06:52
@luviiit I can't even resolve that host:

```
> ping proxy.iiit.ac.in
ping: cannot resolve proxy.iiit.ac.in: Unknown host
```

```
> nmap proxy.iiit.ac.in

Starting Nmap 7.01 ( https://nmap.org ) at 2016-02-25 22:49 PST
Failed to resolve "proxy.iiit.ac.in".
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.40 seconds
```

```
> curl -x proxy.iiit.ac.in:8080 google.com
curl: (5) Could not resolve proxy: proxy.iiit.ac.in
```

So an error is not surprising. Please make sure it's not a local hostname or anything.

**Comment by zmwangx** [comment] 2016-02-26 06:54
Also, I would appreciate it if you instead comment on the PR than in this closed issue thread.

**Comment by jarun** [comment] 2016-02-26 06:54
@zmwangx he is inside the intranet.
@luviiit can you share the results of the same nmap and curl commands here?

**Comment by zmwangx** [comment] 2016-02-26 06:55
> he is inside the intranet.

Yep probably. That's why I'm saying "please make sure it's not a local hostname or anything", because there's no way I can troubleshoot from outside.

**Comment by jarun** [comment] 2016-02-26 06:57
I don't think he can find a open proxy for us. We need to troubleshoot from outside, if possible.

**Comment by zmwangx** [comment] 2016-02-26 07:01
Fair point. I went to iiit.ac.in, and looks like it's an academic institution. I find this rather curious. Why is its proxy server only accessible from inside? My institution's proxy server is used from the outside to gain access to, for instance, library electronic subscriptions. Anyway, it's useless for testing purposes because there's an authentication gate guarded by 2FA, so even if I implement HTTP Basic Authentication it still won't work.

**Comment by jarun** [comment] 2016-02-26 07:03
I guess you need to request OP to run tests for you.

**Comment by jarun** [comment] 2016-02-26 13:37
Please continue the discussion on #37.
